source "$HOME/.bashrc"

##
# Your previous /Users/awalters/.bash_profile file was backed up as /Users/awalters/.bash_profile.macports-saved_2012-02-04_at_11:17:15
##

# MacPorts Installer addition on 2012-02-04_at_11:17:15: adding an appropriate PATH variable for use with MacPorts.
export PATH=/opt/local/bin:/opt/local/sbin:$PATH
# Finished adapting your PATH environment variable for use with MacPorts.

