" *** NEW CONFIG ***
" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible
" required for Vundle
filetype off 

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required for Vundle
Bundle 'gmarik/vundle'

" My Bundles here:
" original repos on github
Bundle 'mileszs/ack.vim'
Bundle 'juvenn/mustache.vim'
Bundle 'hashrocket/slurper'
Bundle 'msanders/snipmate.vim'
Bundle 'kchmck/vim-coffee-script'
Bundle 'vim-scripts/VimClojure'
Bundle 'tpope/vim-cucumber'
Bundle 'tpope/vim-endwise'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-haml'
Bundle 'digitaltoad/vim-jade'
Bundle 'pangloss/vim-javascript'
Bundle 'tpope/vim-markdown'
Bundle 'tsaleh/vim-matchit'
Bundle 'ornicar/vim-mru'
Bundle 'tpope/vim-rails'
Bundle 'vim-ruby/vim-ruby'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-unimpaired'
Bundle 'git://git.wincent.com/command-t.git'
Bundle 'kikijump/tslime.vim'

" required for Vundle
filetype plugin indent on

" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set expandtab

" Always display the status line
set laststatus=2

" Display incomplete commands
set showcmd

" Color scheme
colorscheme railscasts
" highlight NonText guibg=#060606
" highlight Folded  guibg=#0A0A0A guifg=#9090D0

" Numbers
set number
set numberwidth=5

" Syntax Highlighting
syntax on
set hlsearch

" Display extra whitespace
set list 
set listchars=tab:>-,trail:.

" case only matters with mixed case expressions
set ignorecase
set smartcase

" Tab completion options
" (only complete to the longest unambiguous match, and show a menu)
set completeopt=longest,menu
set wildmode=list:longest,list:full

" Load indent files, to automatically do language-dependent indenting.
filetype plugin indent on

" Leader + Custom Mappings
let mapleader = ","

" -- Open Explore in current buffer
map <Leader>e :Explore<CR>

" -- Quickly edit vimrc
map <Leader>qq :sp ~/.vimrc<CR><C-W>_ 

" -- Open MRU (Most Recently Used plugin)
map <Leader>m :MRU 

" -- Close current window
map <Leader>x :close<CR>

" -- Close quickfix window
map <Leader>c :cclose<CR>

" -- Coffee Script
map <Leader>cr :CoffeeRun<CR>
map <Leader>cc :CoffeeCompile<CR>
map <Leader>cm :CoffeeMake<CR>

" -- Toggle Line Numbers
map <Leader>n :set number!<CR>

" -- Fugitive
map <Leader>gs :Gstatus<CR>
map <Leader>gb :Gblame<CR>
map <Leader>gd :Gdiff<CR>
map <Leader>gw :Gwrite<CR>
" END CUSTOM LEADER COMMANDS

" Command-T Settings
let g:CommandTMaxFiles=20000

" autocmds
if has("autocmd")
  autocmd! BufWritePost .vimrc source %
endif " has("autocmd")

" Project based config
if filereadable(".custom/vim.vimrc")
  source .custom/vim.vimrc
endif


" Local config
if filereadable(".vimrc.local")
  source .vimrc.local
endif
