# ENV VARIABLES
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"
export SVN_EDITOR="mvim"
export ERL_LIBS=/opt/erlang-libs
export RDOCOPT="-S -f html -T hanna"
export CLASSPATH="$CLASSPATH:/usr/local/Cellar/clojure-contrib/1.1.0/clojure-contrib.jar"
# completion
# automatically enter directories without cd
setopt auto_cd

export EDITOR='mvim -f'
export JAVA_HOME='/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Home'

# aliases
if [ -e "$HOME/.aliases" ]; then
  source "$HOME/.aliases"
fi

# use incremental search
bindkey ^R history-incremental-search-backward

# use emacs binding
bindkey -e 

# expand functions in the prompt
setopt prompt_subst

# prompt
export PS1='$(git_prompt_info)[${SSH_CONNECTION+"%{$fg_bold[green]%}%n@%m:"}%{$fg_bold[green]%}%2c%{$reset_color%}] '

# ignore duplicate history entries
setopt histignoredups

# keep more history
export HISTSIZE=200

# rvm-install added line:
if [[ -s ~/.rvm/scripts/rvm ]] ; then source ~/.rvm/scripts/rvm ; fi


## Completions
autoload -U compinit
compinit -C
## completions ####
autoload -U zstyle+
## General completion technique
## complete as much u can ..
#zstyle ':completion:*' completer _complete _list _oldlist _expand _ignored _match _correct _approximate _prefix
## complete less
zstyle ':completion:*' completer _expand _complete _list _ignored _approximate
## complete minimal
#zstyle ':completion:*' completer _complete _ignored
